### ISSUE TITLE
can i specify the port i want the fake server to be bound to ?

### ISSUE THREAD

**Issue by Kyr4l** [ei-projects/eimaster#1]
hi, great project i see, i hope it's not abandonned

**Comment by koteyur** [comment]
Hi, tbh I haven't working on it for quite a while, but if there're bugs I'll fix them of course.

I took a quick look and it seems there's no way to specify the port, but it should be a fairly simple fix. But if it's not a secret, what's your use case for this? Fake server makes master server think that there's a server, but in fact there's no one. This command is mostly to check if master server works fine or not.

**Comment by Kyr4l** [comment]
the use case for me is to make connection tests along with firewall tests
i use it to check the master servers as well
i'm doing some reverse engineering of the game

**Comment by koteyur** [comment]
I see, make sense.

I've added `-saddr` argument to specify source address:
```
$ ./eimaster client send -saddr :8888 vps.gipat.ru
...
$ ./eimaster client get vps.gipat.ru
Name         Players  Allod  Password  Address                Ping   Quest
Fake server  0 / 13   5      true      1.2.3.4:8888           0      Fake quest
```

**Comment by Kyr4l** [comment]
thanks :> amazing job 
do you have any plans for this project ? such as making dedicated game servers or something that can stay on 24/7 ?

**Comment by koteyur** [comment]
Not much. I have a project by making proxy server to let people create accessible server behind NAT the way, that other clients don't need to install anything (only user-server). But I don't work on it actively, so no idea when I release it.

Dedicated server can be done by patching original engine in order to make it standalone executable to run servers. But that's too much work, so I don't plan to start working on it. Writing server from scratch is even more difficult (basically, re-implementing half of the game).
